export const UPDATE_WHEN = 'UPDATE_WHEN';
export const UPDATE_WHERE = 'UPDATE_WHERE';
export const UPDATE_STORY = 'UPDATE_STORY';
export const UPDATE_PEOPLE_PRESENT = 'UPDATE_PEOPLE_PRESENT';
export const UPDATE_FEELS_BEFORE = 'UPDATE_FEELS_BEFORE';
export const UPDATE_FEELS_NOW = 'UPDATE_FEELS_NOW';
export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
